---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: required
dist: trusty

addons:
  chrome: stable

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - yarn install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - yarn try $EMBER_TRY_SCENARIO --skip-cleanup

notifications:
  email: false

jobs:
  fail_fast: true

  include:
    - stage: Locked Dependencies
      name: Lint
      script: yarn lint:js
    - name: Tests
      script: yarn test
    - name: Node Tests
      script: yarn node-test
    - name: Type Declarations
      script: yarn dtslint

    - stage: Floating Dependencies
      name: Tests
      # ember-try runs --no-lockfile install by default
      env: EMBER_TRY_SCENARIO=ember-default
    - name: Node Tests
      install: yarn install --no-lockfile --non-interactive
      script: yarn node-test

    - stage: Scenarios
      env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=typescript
    - env: EMBER_TRY_SCENARIO=production
    - env: EMBER_TRY_SCENARIO=stage-1-transforms
    - env: EMBER_TRY_SCENARIO=forced-stage-1-build
    - env: EMBER_TRY_SCENARIO=throw-on-computed-override

